version: "2.16"
services:
  eureka:
    image: ${MS_IMAGE_PREFIX}/eureka:${MS_IMAGE_TAG}
    container_name: eureka
#    ports:
#      - '8761:8761' # 默认不开启
    environment:
      REDIS_HOST: ${MS_REDIS_HOST}
      REDIS_PORT: ${MS_REDIS_PORT}
      REDIS_PASSWORD: ${MS_REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8761" ]
      interval: 6s
      timeout: 10s
      retries: 50
    restart: always
    volumes:
      - ms-conf:${MS_BASE}/metersphere/conf
      - ms-logs:${MS_BASE}/metersphere/logs
      - ms-data:${MS_BASE}/metersphere/data
    mem_limit: ${MS_EUREKA_MEM_LIMIT:-536870912} # default 512m bytes
    networks:
      - ms-network
