version: "2.1"
services:
  ms-server:
    image: ${MS_PREFIX}/metersphere-server:${MS_TAG}
    container_name: ms-server
    environment:
      HOST_HOSTNAME: $HOSTNAME
    ports:
      - ${MS_PORT}:8081
    volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-logs:/opt/metersphere/logs
    mem_limit: 1024m
    networks:
      - ms-network
#MS_EXTERNAL_MYSQL=false      
    depends_on:
      - mysql

  ms-data-streaming:
    image: ${MS_PREFIX}/metersphere-data-streaming:${MS_TAG}
    container_name: ms-data-streaming
    environment:
      HOST_HOSTNAME: $HOSTNAME
    ports:
      - 7777:7777
    volumes:
      - ./conf/metersphere.properties:/opt/metersphere/conf/metersphere.properties
      - ${MS_BASE}/metersphere/logs/data-streaming:/opt/metersphere/logs/data-streaming
    networks:
      - ms-network
#MS_EXTERNAL_KAFKA=false      
    depends_on:
      - kafka