version: "2.1"
services:
  local-selenium-grid:
    image: ${MS_IMAGE_PREFIX}/seleniarm-grid-all:4.8.0-20230302
    container_name: local-selenium-grid
    shm_size: 4gb
    entrypoint: bash -c '[ ! -f /home/seluser/language ] && sudo sed -i -e "s/# $$LANG.*/$$LANG UTF-8/" /etc/locale.gen && sudo dpkg-reconfigure --frontend=noninteractive locales && sudo update-locale LANG=$$LANG && touch /home/seluser/language; /opt/bin/entry_point.sh'
    environment:
      - TZ=Asia/Shanghai
      - SE_EVENT_BUS_HOST=127.0.0.1
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_HUB_PORT=4444
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - browser=chrome
      - JAVA_OPTS=-Xmx512m
      - LANG=zh_CN.UTF-8
    ports:
      - "4444:4444"
      # - "5900:5900" # no vnc by default, password: secret
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444" ]
      interval: 6s
      timeout: 5s
      retries: 50
    restart: always
    networks:
      - ms-network
