version: "2.1"
services:
  node-controller:
    image: ${MS_IMAGE_PREFIX}/node-controller:${MS_IMAGE_TAG}
    container_name: node-controller
    environment:
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
      RUN_AS_NON_ROOT_USER: 'true'
    command: sh -c 'sed -i "s/:101:/:${MS_DOCKER_GID:-101}:/g" /etc/group; /deployments/run-java.sh'
    ports:
      - ${MS_NODE_CONTROLLER_PORT}:8082
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8082" ]
      interval: 6s
      timeout: 5s
      retries: 50
    volumes:
      - ${MS_BASE}/metersphere/data/app:/opt/metersphere/data/app
      - ${MS_BASE}/metersphere/logs/node-controller:/opt/metersphere/logs/node-controller
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: ${MS_NC_MEM_LIMIT:-1073741824} # default 1g bytes
    restart: always
    networks:
      - ms-network

