version: "2.1"
services:
  ms-node-controller:
    image: ${MS_PREFIX}/ms-node-controller:${MS_TAG}
    container_name: ms-node-controller
    environment:
      HOST_HOSTNAME: $HOSTNAME
      KAFKA_PARTITIONS: 1
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      JMETER_IMAGE: ${MS_PREFIX}/jmeter-master:0.0.7
    ports:
      - ${MS_NODE_CONTROLLER_PORT}:8082
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8082"]
      interval: 6s
      timeout: 5s
      retries: 10
    volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-jmeter-data:/jmeter
      - ms-logs:/opt/metersphere/logs
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 1024m
    networks:
      - ms-network

volumes:
  ms-jmeter-data:
    driver_opts:
      type: none
      device: ${MS_BASE}/metersphere/data/jmeter
      o: bind