version: "2.1"
services:
  ms-node-controller:
    image: ${MS_PREFIX}/ms-node-controller:${MS_TAG}
    container_name: ms-node-controller
    environment:
      HOST_HOSTNAME: $HOSTNAME
      JMETER_DATA_PATH: ${MS_BASE}/${MS_JMETER_DATA_PATH}
    ports:
      - ${MS_NODE_CONTROLLER_PORT}:8082
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8082"]
      interval: 6s
      timeout: 5s
      retries: 10
    volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-jmeter-data:${MS_BASE}/${MS_JMETER_DATA_PATH}
      - ms-logs:/opt/metersphere/logs
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 1024m
    networks:
      - ms-network

volumes:
  ms-jmeter-data:
    driver_opts:
      type: none
      device: ${MS_BASE}/${MS_JMETER_DATA_PATH}
      o: bind
