version: "2.1"
services:
  metersphere-server:
    image: registry.fit2cloud.com/metersphere/metersphere-server:${metersphere_image_tag}
    container_name: metersphere-server
    environment:
      HOST_HOSTNAME: $HOSTNAME
    ports:
      - ${metersphere_server_port}:8081
    volumes:
      - metersphere-conf:/opt/metersphere/conf
      - metersphere-logs:/opt/metersphere/logs
    mem_limit: 1024m
    networks:
      - ms-network
    depends_on:
      - mysql