version: "2.1"
services:
  ms-server:
    image: registry.fit2cloud.com/metersphere/metersphere-server:${metersphere_image_tag}
    container_name: ms-server
    environment:
      HOST_HOSTNAME: $HOSTNAME
    ports:
      - ${metersphere_server_port}:8081
    volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-logs:/opt/metersphere/logs
    mem_limit: 1024m
    networks:
      - ms-network
#external_mysql=false      
    depends_on:
      - mysql

  ms-data-streaming:
    image: registry.fit2cloud.com/metersphere/metersphere-data-streaming:${metersphere_image_tag}
    container_name: ms-data-streaming
    environment:
      HOST_HOSTNAME: $HOSTNAME
    ports:
      - 7777:7777
    volumes:
      - ./conf/metersphere.properties:/opt/metersphere/conf/metersphere.properties
      - ${base_dir}/metersphere/logs/data-streaming:/opt/metersphere/logs/data-streaming
    networks:
      - ms-network
#external_kafka=false      
    depends_on:
      - kafka