version: "2.1"
services:
  zookeeper:
    image: 'registry.fit2cloud.com/metersphere/zookeeper:3'
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - 'ms-zookeeper-data:/bitnami'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - ms-network
  kafka:
    image: 'registry.fit2cloud.com/metersphere/kafka:2'
    container_name: kafka
    ports:
      - '${kafka_port}:${kafka_port}'
    volumes:
      - 'ms-kafka-data:/bitnami'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:${kafka_port}
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${kafka_host}:${kafka_port}
    depends_on:
      - zookeeper
    networks:
      - ms-network
volumes:
  ms-zookeeper-data:
    driver_opts:
      type: none
      device: ${base_dir}/metersphere/data/zookeeper
      o: bind
  ms-kafka-data:
    driver_opts:
      type: none
      device: ${base_dir}/metersphere/data/kafka
      o: bind